### ISSUE TITLE
Failed to serialize 'FanoutSearch.Action' to a type object.

### ISSUE THREAD

**Issue by BenDerPan** [microsoft/GraphEngine#168]
my environment:
Ubuntu16.04 x64
.NetCore 2.1.4
GraphEngine.Core 1.0.9083  (I build it myself,The NuGet package outdated.)
GraphEngine.LIKQ 1.0.9083

My main test code:
`           Global.LocalStorage.LoadStorage();
            TrinityConfig.HttpPort = 80;
            FanoutSearchModule.EnableExternalQuery(true);
            FanoutSearchModule.SetQueryTimeout(3000);
            FanoutSearchModule.RegisterIndexService(Indexer);
            FanoutSearchModule.RegisterExpressionSerializerFactory(ExpressionSerializerFactory);
            TrinityServer server=new TrinityServer();
            server.RegisterCommunicationModule<FanoutSearchModule>();
            server.Start();`

the exception throws at 
`
    public class ExpressionSerializer:IExpressionSerializer
    {
        private static XmlSerializer m_serializer = null;
        private static NodeFactory m_factory = null;

        public ExpressionSerializer()
        {
            m_serializer=new XmlSerializer();
            m_serializer.AddKnownType(typeof(FanoutSearch.Action));
            m_factory=new NodeFactory();
        }
        
        public string Serialize(Expression pred)
        {
            //Exception throws here
            return pred.ToXml(m_factory,m_serializer);
        }

        public Func<ICellAccessor, Action> DeserializeTraverseAction(string pred)
        {
            var func_exp = m_serializer.Deserialize<LambdaExpressionNode>(pred)
                .ToExpression<Func<ICellAccessor, FanoutSearch.Action>>();
            return func_exp.Compile();
        }

        public Func<ICellAccessor, bool> DeserializeOriginPredicate(string pred)
        {
            var fun_exp = m_serializer.Deserialize<LambdaExpressionNode>(pred)
                .ToExpression<Func<ICellAccessor, bool>>();
            return fun_exp.Compile();
        }
    }`

Exceptions Trace:
Unhandled Exception: System.Runtime.Serialization.SerializationException: Failed to serialize 'FanoutSearch.Action' to a type object.
   at Serialize.Linq.Nodes.TypeNode.ToType(IExpressionContext context)
   at Serialize.Linq.Nodes.ConstantExpressionNode.set_Value(Object value)
   at Serialize.Linq.Nodes.ConstantExpressionNode.Initialize(ConstantExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1..ctor(INodeFactory factory, TExpression expression)
   at Serialize.Linq.Nodes.ConstantExpressionNode..ctor(INodeFactory factory, ConstantExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode.Initialize(LambdaExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1..ctor(INodeFactory factory, TExpression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode..ctor(INodeFactory factory, LambdaExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Extensions.ExpressionExtensions.ToText(Expression expression, INodeFactory factory, ITextSerializer serializer)
   at Serialize.Linq.Extensions.ExpressionExtensions.ToXml(Expression expression, INodeFactory factory, IXmlSerializer serializer)
   at People_LIKQ.ExpressionSerializer.Serialize(Expression pred) in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/ExpressionSerializer.cs:line 30
   at FanoutSearch.ExpressionSerializer.Serialize(Expression pred)
   at FanoutSearch.FanoutSearchDescriptor.<>c.<Serialize>b__22_0(Expression pred)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FanoutSearch.FanoutSearchDescriptor.Serialize()
   at FanoutSearch.FanoutSearchDescriptor._ExecuteQuery()
   at FanoutSearch.FanoutSearchDescriptor.GetEnumerator()
   at People_LIKQ.Program.LikqQurety() in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/Program.cs:line 73
   at People_LIKQ.Program.Main(String[] args) in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/Program.cs:line 37

**Comment by chaosddp** [comment]
For dotnet core you should add Serializer.Linq  as dependency for both Trinity and Likq project, this is an implement issue of Serializer.Linq.

Also @yatli, i found that my previous commit was merged to one project file, but lost the Serializer.Linq  for dotnet core.

**Comment by chaosddp** [comment]
Add code [link](https://github.com/esskar/Serialize.Linq/blob/master/src/Serialize.Linq.NetCore11/Internals/AppDomain.cs) for reference, in method 'IsCandidateCompilationLibrary'.

**Comment by yatli** [comment]
@chaosddp thanks for your input! I’m also wondering how to make this work with coreclr. As for Serializer.Linq, I think coreclr references are transitive so you only have to add the reference at the leaf.

**Comment by yatli** [comment]
Are you sure a reference to Serialize.Linq is mandatory on LIKQ itself? Looks like it’s got some black magic in that library wrt assembly loading

**Comment by yatli** [comment]
Update: @chaosddp I believe this is where the code pattern you referenced came from:

https://stackoverflow.com/questions/43965820/replacement-for-appdomain-getloadedassemblies-in-net-core
http://www.michael-whelan.net/replacing-appdomain-in-dotnet-core/

It's a replacement to search for all loaded assemblies prior to `netstandard2.0`.

**Comment by BenDerPan** [comment]
@chaosddp  I  pull the newest source code and added Serializer.Linq as dependency for both Trinity.Core and Likq project, and rebuild GraphEngine.Core GraphEngine.LIKQ, and add refrence Serializer.Linq in both TSL and Program project, But I still get the same error, and some new error output "ghashtable.c:324: assertion 'hash != NULL' failed" as below:

Unhandled Exception: System.Runtime.Serialization.SerializationException: Failed to serialize 'FanoutSearch.Action' to a type object.
   at Serialize.Linq.Nodes.TypeNode.ToType(IExpressionContext context)
   at Serialize.Linq.Nodes.ConstantExpressionNode.set_Value(Object value)
   at Serialize.Linq.Nodes.ConstantExpressionNode.Initialize(ConstantExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1..ctor(INodeFactory factory, TExpression expression)
   at Serialize.Linq.Nodes.ConstantExpressionNode..ctor(INodeFactory factory, ConstantExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode.Initialize(LambdaExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1..ctor(INodeFactory factory, TExpression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode..ctor(INodeFactory factory, LambdaExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Extensions.ExpressionExtensions.ToText(Expression expression, INodeFactory factory, ITextSerializer serializer)
   at Serialize.Linq.Extensions.ExpressionExtensions.ToXml(Expression expression, INodeFactory factory, IXmlSerializer serializer)
   at People_LIKQ.ExpressionSerializer.Serialize(Expression pred) in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/ExpressionSerializer.cs:line 30
   at FanoutSearch.ExpressionSerializer.Serialize(Expression pred)
   at FanoutSearch.FanoutSearchDescriptor.<>c.<Serialize>b__22_0(Expression pred)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FanoutSearch.FanoutSearchDescriptor.Serialize()
   at FanoutSearch.FanoutSearchDescriptor._ExecuteQuery()
   at FanoutSearch.FanoutSearchDescriptor.GetEnumerator()
   at People_LIKQ.Program.LikqQurety() in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/Program.cs:line 73
   at People_LIKQ.Program.Main(String[] args) in /home/coder/Documents/NetCore/LIKQ-Examples/People-LIKQ/Program.cs:line 37
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed
ghashtable.c:324: assertion 'hash != NULL' failed

**Comment by chaosddp** [comment]
@yatli, yes that the problem, and i just remembered that we can reference System.Runtime for LIKQ project as current one, i will have a try, then update later

@BenDerPan i will have a try, since i still keep an old version without updating.

**Comment by chaosddp** [comment]
@yatli i found the issue that Serialize.Linq trying to load assembly for 'GraphEngine.LIKQ', but actually it should be "FanoutSearch", at line 32 [here](https://github.com/esskar/Serialize.Linq/blob/master/src/Serialize.Linq.NetCore11/Internals/AppDomain.cs), seems like RuntimeLibary using PackageId as name here.

**Comment by chaosddp** [comment]
@BenDerPan as a temporary workaround you can change the packageid of FanoutSearch to 'FanoutSearch', then the tests will pass.

**Comment by yatli** [comment]
@chaosddp you rock! I'm submitting an issue to Serialize.Linq to reference your findings. For now, I'll set the assembly name to GraphEngine.LIKQ to work around this.

**Comment by esskar** [comment]
hey, what do you want me to change in Serialize.Linq?

**Comment by yatli** [comment]
hi @esskar! I believe we understand the code and our workaround will address this issue temporarily. We do hope that the assembly loader behaves consistently with `netfx` and `netstandard`. I know it's a bit of a trouble for `netcore11` because there were no proper support for assembly enumeration, but anyway my suggestion on this is to:

1. add a new target `netstandard2.0` which does support assembly enumeration from AppDomain.
2. for `netcore11`, try to figure out the assembly name from the package id returned from `using Microsoft.Extensions.DependencyModel`.

**Comment by PhilPJL** [comment]
@yatli 
I just hit this exception.  Is this something you'll be able to fix soon, so the unit tests work?

**Comment by yatli** [comment]
@PhilPJL yup, in a day or two I’ll get to work on this.

**Comment by esskar** [comment]
i just published [Serialize.Linq 1.7.0](https://www.nuget.org/packages/Serialize.Linq/) with support for .net standard 1.3 and 2.0
does this help with your issue?

**Comment by yatli** [comment]
ooh @esskar that's great news! trying rightaway, will report back in a few mins. tried to work on this issue two hours ago and it's still 1.6 :D

**Comment by yatli** [comment]
@esskar just confirmed version 1.7.0 is working for `netcoreapp2.0`. thank you for your quick update!

**Comment by esskar** [comment]
i am glad i could help, and thanks for using my library. i was totally unaware of that.
