### ISSUE TITLE
Message=Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#190]
I got a bit further down the road.

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=System.Data.SQLite
  StackTrace:
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize()
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at freebase_likq.Program.BuildIndex(String sqlite_db_path) in L:\Source\Repos\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 77
   at freebase_likq.Program.Initialize() in L:\Source\Repos\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 65
   at freebase_likq.Program.Main(String[] args) in L:\Source\Repos\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 29

![image](https://user-images.githubusercontent.com/5692812/39143170-e1b84d60-46e1-11e8-8d65-3e7fb9e80baa.png)

![image](https://user-images.githubusercontent.com/5692812/39143175-e79d5842-46e1-11e8-931a-84b75b7e64f8.png)

**Comment by yatli** [comment]
@leasunhy got time to look into this?

**Comment by TaviTruman** [comment]
Albeit the problem is a simple one I have yet tracked down where the SQLite assembly went. I am starting over with a clean environment. I have tried to get this demo to work now on three machines and I get a different result each time. Most likely that points to some oddities in my dev environment so I have cleaned that up. Trying to get the build to work again.

**Comment by TaviTruman** [comment]
Looks like the SQLite .NET pre-compiled interop assemblies are missing. I found the website and when I have time I will download the assemblies and try running the sample.

**Comment by TaviTruman** [comment]
I did a search for the missing SQLite.Interop.dll and found a great many copies of the assembly on my machine. I downloaded .NET pre-compiled assembles from here: http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki. I copy the dll and placed it in the root directory and the app runs.
