### ISSUE TITLE
GraphEngine runtime error: The type initializer for 'Trinity.Global' threw an exception

### ISSUE THREAD

**Issue by Vasyl-Za** [microsoft/GraphEngine#225]
Steps to recreate;
1. Build latest code from master (2.0.9522)

2. Update DistributedHashtable sample app to use GraphEngine.Core package version 2.0.9522 from local Nuget repository.

3. Run "DistributedHashtable -s"

4. Runtime Exception: 
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Trinity.Global' threw an exception.
  Source=Trinity.Core

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'Trinity': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

**Comment by yatli** [comment]
hi @selepko !

Which target framework are you using? `net46`?

**Comment by Vasyl-Za** [comment]
Hi Yatao Li,

The target framework in DistributedHashtable VS projest is 4.7.2.

Thank you!

**Comment by yatli** [comment]
please post your .csproj file content. I started with an empty `4.7` project and did a `Global.LocalStorage.LoadStorage` and it works fine:


```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.props" Condition="Exists('..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{59092A3D-0719-41BB-A173-CBAE84A5D025}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp4</RootNamespace>
    <AssemblyName>ConsoleApp4</AssemblyName>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.ObjectPool, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Extensions.ObjectPool.2.0.0\lib\netstandard2.0\Microsoft.Extensions.ObjectPool.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="Trinity.Core, Version=2.0.9520.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\GraphEngine.Core.2.0.9520\lib\net461\Trinity.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
    <None Include="TrinityConfig.Schema.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.props'))" />
    <Error Condition="!Exists('..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.targets'))" />
  </Target>
  <Import Project="..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.targets" Condition="Exists('..\packages\GraphEngine.Core.2.0.9520\build\GraphEngine.Core.targets')" />
</Project>
```

**Comment by yatli** [comment]
btw, the package version is now auto updated -- we're actually on the same commit :)

**Comment by yatli** [comment]
check if `Trinity.dll` is present in your output folder.

**Comment by yatli** [comment]
tip: use 3 '`' to escape chunky content

**Comment by Vasyl-Za** [comment]
```<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.props" Condition="Exists('..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{EF22336B-4CEE-4B92-A325-704BCC2DAC76}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>DistributedHashtable</RootNamespace>
    <AssemblyName>DistributedHashtable</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.ObjectPool, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Extensions.ObjectPool.2.0.0\lib\netstandard2.0\Microsoft.Extensions.ObjectPool.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\packages\Newtonsoft.Json.11.0.2\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.ValueTuple.4.5.0\lib\net47\System.ValueTuple.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Trinity.Client, Version=2.0.9522.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\GraphEngine.Client.2.0.9522\lib\net461\Trinity.Client.dll</HintPath>
    </Reference>
    <Reference Include="Trinity.Core, Version=2.0.9522.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\GraphEngine.Core.2.0.9522\lib\net461\Trinity.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="DistributedHashtableServer.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config">
      <SubType>Designer</SubType>
    </None>
    <None Include="TrinityConfig.Schema.xsd">
      <SubType>Designer</SubType>
    </None>
    <TslCodegen Include="DistributedHashtable.tsl" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.props'))" />
    <Error Condition="!Exists('..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.targets'))" />
  </Target>
  <Import Project="..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.targets" Condition="Exists('..\packages\GraphEngine.Core.2.0.9522\build\GraphEngine.Core.targets')" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>```

**Comment by Vasyl-Za** [comment]
```Trinity.dll``` is present in my output folder. Version is not available, The size is: 432,640 bytes.

Thanks for the 3 '```' tip!

**Comment by yatli** [comment]
could you try debug the program and give a detailed stacktrace of the exception? I now see that it's complaining about a procedure in the DLL, we need to know which one it is.

**Comment by Vasyl-Za** [comment]
Not much in the stack trace:

Message: ```The type initializer for 'Trinity.Global' threw an exception.```

StackTrace:
```
   at Trinity.Global.get_MyAssemblyPath()
   at DistributedHashtable.Program.Main(String[] args) in C:\GraphEngine\z-playground\TMP\DistributedHashtable\DistributedHashtable\Program.cs:line 20
```

**Comment by yatli** [comment]
you've got to inspect the inner exception.

**Comment by yatli** [comment]
um, no need to inspect that I think -- my freshly-built Trinity.dll is `882 KB (903,168 bytes)`. there could be a problem in your build workflow, or the nuget package is stale.

**Comment by Vasyl-Za** [comment]
On my machine: there is ```Trinity.dll``` in the \lib folder: no version, size = 893,952 bytes. ```Trinity.dll``` in the \build folder: no version, size = 432,640 bytes.

**Comment by Vasyl-Za** [comment]
Hi Yatao Li,

I rebuilt everything. Package version increased: now it is 2.0.9523 coming from package source 'Graph Engine OSS Local'. Unfortunately the same runtime exception.

Inner Exception StackTrace:

```   at Trinity.TrinityC.__INIT_TRINITY_C__(Char* pAssemblyPath)
   at Trinity.TrinityC.Init()
   at Trinity.Global.Initialize_impl(String config_file)
   at Trinity.Global..cctor()```

**Comment by yatli** [comment]
hi @selepko, yeah it's still the same problem.. I'm wondering where's that 400+kb dll coming from.

**Comment by Vasyl-Za** [comment]
Hi @yatli  -- yes, it is still a problem.

Regarding:

```> um, no need to inspect that I think -- my freshly-built Trinity.dll is `882 KB (903,168 bytes)`. there could be a problem in your build workflow, or the nuget package is stale.```

Apparently, there are no problem with the build and no stale packages. I build simplistic console application only with:

```                TrinityConfig.AddServer(new Trinity.Network.ServerInfo("127.0.0.1", 7777, Global.MyAssemblyPath, Trinity.Diagnostics.LogLevel.Error)); ```

and freshly built GraphEngine.Core package. No problem running binaries on Windows 8.1 and Windows 10 machine. The same application blows up on Windows 7 Professional SP 1 and on Windows Server 2008 R2 with 

```Unable to load DLL 'Trinity': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)```

internal Exception. 

My wild guess: there are subtle differences beetween the way absolute / relative pathe is handled in C++ code, but this is just a guess: I am not familiar with the code.

**Comment by Vasyl-Za** [comment]
> hi @selepko, yeah it's still the same problem.. I'm wondering where's that 400+kb dll coming from.

Trinity.dll, size 432,640 bytes
Trinity.exp, size 15,726 bytes
Trinity.lib, size 26,658 bytes

appear on my machine after the build in the .\buid directory. In my understanding this Trinity.dll is packaged in the GraphEngine.Core package.

**Comment by yatli** [comment]
what's the output of `& "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\dumpbin.exe" /EXPORTS Trinity.dll` (you may have to adjust the path to `dumpbin`

**Comment by Vasyl-Za** [comment]
The output of  ```C:\VS14\VC\bin\amd64\dumpbin /EXPORTS Trinity.dll => Trinity.dumpbin.txt```:

```
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Trinity.dll

File Type: DLL

  Section contains the following exports for Trinity.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
         119 number of functions
         119 number of names

    ordinal hint RVA      name

          1    0 00018410 AlignedAlloc = AlignedAlloc
          2    1 00017A10 AwaitRequest = AwaitRequest
          3    2 00018420 CAddCell = CAddCell
          4    3 00018430 CCellCount = CCellCount
          5    4 00038F10 CClientDisableSendBuffer = CClientDisableSendBuffer
          6    5 00018440 CContains = CContains
          7    6 00018460 CDispose = CDispose
          8    7 00018470 CGetCellType = CGetCellType
          9    8 00018480 CGetLockedCellInfo4AddOrUseCell = CGetLockedCellInfo4AddOrUseCell
         10    9 00018490 CGetLockedCellInfo4CellAccessor = CGetLockedCellInfo4CellAccessor
         11    A 000184A0 CGetLockedCellInfo4LoadCell = CGetLockedCellInfo4LoadCell
         12    B 0002AEA0 CGetStorageSlot = CGetStorageSlot
         13    C 000184B0 CGetTrinityImageSignature = CGetTrinityImageSignature
         14    D 00038F20 CHandshake = CHandshake
         15    E 000184C0 CInitialize = CInitialize
         16    F 00038F30 CLargeObjectThreshold = CLargeObjectThreshold
         17   10 000184D0 CLoadStorage = CLoadStorage
         18   11 000184F0 CLocalMemoryStorageEnumeratorAllocate = CLocalMemoryStorageEnumeratorAllocate
         19   12 00018500 CLocalMemoryStorageEnumeratorDeallocate = CLocalMemoryStorageEnumeratorDeallocate
         20   13 00018510 CLocalMemoryStorageEnumeratorMoveNext = CLocalMemoryStorageEnumeratorMoveNext
         21   14 00018520 CLocalMemoryStorageEnumeratorReset = CLocalMemoryStorageEnumeratorReset
         22   15 00018530 CLockedGetCellSize = CLockedGetCellSize
         23   16 00040D10 CLogCloseFile = CLogCloseFile
         24   17 00040D20 CLogCollectEntries = CLogCollectEntries
         25   18 00040E30 CLogFlush = CLogFlush
         26   19 00040E40 CLogInitialize = CLogInitialize
         27   1A 00040FC0 CLogOpenFile = CLogOpenFile
         28   1B 000410A0 CLogSetEchoOnConsole = CLogSetEchoOnConsole
         29   1C 000411B0 CLogSetLogLevel = CLogSetLogLevel
         30   1D 00041280 CLogUninitialize = CLogUninitialize
         31   1E 00041290 CLogWriteLine = CLogWriteLine
         32   1F 00018540 CLoggedAddCell = CLoggedAddCell
         33   20 00018550 CLoggedRemoveCell = CLoggedRemoveCell
         34   21 00018560 CLoggedSaveCell = CLoggedSaveCell
         35   22 00018570 CLoggedUpdateCell = CLoggedUpdateCell
         36   23 00018580 CMTHashCommittedMemorySize = CMTHashCommittedMemorySize
         37   24 00038F40 CReadOnly = CReadOnly
         38   25 00018590 CReleaseCellLock = CReleaseCellLock
         39   26 000185A0 CRemoveCell = CRemoveCell
         40   27 000185B0 CResetStorage = CResetStorage
         41   28 000185D0 CResizeCell = CResizeCell
         42   29 000185E0 CSaveCell = CSaveCell
         43   2A 000185F0 CSaveStorage = CSaveStorage
         44   2B 00038F50 CSetClientDisableSendBuffer = CSetClientDisableSendBuffer
         45   2C 00038F60 CSetGCDefragInterval = CSetGCDefragInterval
         46   2D 00038F70 CSetHandshake = CSetHandshake
         47   2E 00038F80 CSetLargeObjectThreshold = CSetLargeObjectThreshold
         48   2F 00038FA0 CSetReadOnly = CSetReadOnly
         49   30 000390C0 CSetTrunkCount = CSetTrunkCount
         50   31 00018610 CSetWriteAheadLogFile = CSetWriteAheadLogFile
         51   32 00006AD0 CStartBackgroundThread = CStartBackgroundThread
         52   33 00006AE0 CStopBackgroundThread = CStopBackgroundThread
         53   34 00018620 CThreadContextAllocate = CThreadContextAllocate
         54   35 00018630 CThreadContextDeallocate = CThreadContextDeallocate
         55   36 00018640 CThreadContextSet = CThreadContextSet
         56   37 00018650 CTotalCellSize = CTotalCellSize
         57   38 00018660 CTotalCommittedMemorySize = CTotalCommittedMemorySize
         58   39 00018670 CTrunkCommittedMemorySize = CTrunkCommittedMemorySize
         59   3A 000390D0 CTrunkCount = CTrunkCount
         60   3B 00018680 CUpdateCell = CUpdateCell
         61   3C 00018690 CWriteAheadLog = CWriteAheadLog
         62   3D 000186A0 CWriteAheadLogComputeChecksum = CWriteAheadLogComputeChecksum
         63   3E 000186B0 CWriteAheadLogValidateChecksum = CWriteAheadLogValidateChecksum
         64   3F 000186D0 C_GetLastError = C_GetLastError
         65   40 000186E0 C_aligned_free = C_aligned_free
         66   41 000186F0 C_aligned_malloc = C_aligned_malloc
         67   42 00018700 C_fclose = C_fclose
         68   43 00018710 C_feof = C_feof
         69   44 00018720 C_fflush = C_fflush
         70   45 00018730 C_fread = C_fread
         71   46 00018740 C_free = C_free
         72   47 00018750 C_fwrite = C_fwrite
         73   48 00018760 C_malloc = C_malloc
         74   49 00018770 C_memcmp = C_memcmp
         75   4A 00018780 C_memcpy = C_memcpy
         76   4B 000187A0 C_memmove = C_memmove
         77   4C 000187B0 C_memset = C_memset
         78   4D 000187D0 C_multiply_double_vector = C_multiply_double_vector
         79   4E 000187E0 C_multiply_sparse_double_vector = C_multiply_sparse_double_vector
         80   4F 000187F0 C_realloc = C_realloc
         81   50 00018800 C_wfopen_s = C_wfopen_s
         82   51 00017A20 ClientReceive = ClientReceive
         83   52 00017A30 ClientSend = ClientSend
         84   53 00017A50 ClientSendMulti = ClientSendMulti
         85   54 00017A70 ClientSocketConnect = ClientSocketConnect
         86   55 00017A90 CloseClientSocket = CloseClientSocket
         87   56 00018810 Copy = Copy
         88   57 00017AA0 CreateClientSocket = CreateClientSocket
         89   58 00017AB0 EnterSocketServerThreadPool = EnterSocketServerThreadPool
         90   59 00017AC0 ExitSocketServerThreadPool = ExitSocketServerThreadPool
         91   5A 000390E0 GetStorageCapacityProfile = GetStorageCapacityProfile
         92   5B 00017AE0 RegisterMessageHandler = RegisterMessageHandler
         93   5C 00018820 RestartDefragmentation = RestartDefragmentation
         94   5D 00017B00 SendResponse = SendResponse
         95   5E 00018830 SetDefragmentationPaused = SetDefragmentationPaused
         96   5F 00018930 SetMaxWorkingSet = SetMaxWorkingSet
         97   60 000390F0 SetStorageCapacityProfile = SetStorageCapacityProfile
         98   61 00039100 SetStorageRoot = SetStorageRoot
         99   62 00018940 SetWorkingSetProfile = SetWorkingSetProfile
        100   63 00017B10 ShutdownSocketServer = ShutdownSocketServer
        101   64 00017B20 StartSocketServer = StartSocketServer
        102   65 00017B30 StartWorkerThreadPool = StartWorkerThreadPool
        103   66 00017B50 StopSocketServer = StopSocketServer
        104   67 00018950 TxCAddCell = TxCAddCell
        105   68 00018960 TxCGetCellType = TxCGetCellType
        106   69 00018970 TxCGetLockedCellInfo4AddOrUseCell = TxCGetLockedCellInfo4AddOrUseCell
        107   6A 00018980 TxCGetLockedCellInfo4CellAccessor = TxCGetLockedCellInfo4CellAccessor
        108   6B 00018990 TxCGetLockedCellInfo4LoadCell = TxCGetLockedCellInfo4LoadCell
        109   6C 000189A0 TxCLoggedAddCell = TxCLoggedAddCell
        110   6D 000189B0 TxCLoggedRemoveCell = TxCLoggedRemoveCell
        111   6E 000189C0 TxCLoggedSaveCell = TxCLoggedSaveCell
        112   6F 000189D0 TxCLoggedUpdateCell = TxCLoggedUpdateCell
        113   70 000189E0 TxCReleaseCellLock = TxCReleaseCellLock
        114   71 000189F0 TxCRemoveCell = TxCRemoveCell
        115   72 00018A00 TxCResizeCell = TxCResizeCell
        116   73 00018A10 TxCSaveCell = TxCSaveCell
        117   74 00018A20 TxCUpdateCell = TxCUpdateCell
        118   75 00017B60 WaitForAckPackage = WaitForAckPackage
        119   76 00018AA0 __INIT_TRINITY_C__ = __INIT_TRINITY_C__

Dump of file =
LINK : fatal error LNK1181: cannot open input file '='
```

**Comment by yatli** [comment]
the exports look good to me. not sure why it's complaining about "entry not found"
could you please also attach your build log -- especially for building `Trinity.C`?

**Comment by Vasyl-Za** [comment]
@yatli - build log? You mean output in powershell window or there is a log file written somewhere?

**Comment by Vasyl-Za** [comment]
@yatli: Same excception on Windows Server 2012.

**Comment by yatli** [comment]
the output in powershell should be enough

**Comment by Vasyl-Za** [comment]
@yatli -- It is here:
https://github.com/Vasyl-Za/GraphEngine-Build-20180920/blob/master/vz-build-log.txt

**Comment by yatli** [comment]
thanks @Vasyl-Za for the diagnostic log! however the logs look just fine to me.

> and freshly built GraphEngine.Core package. No problem running binaries on Windows 8.1 and Windows 10 machine. The same application blows up on Windows 7 Professional SP 1 and on Windows Server 2008 R2 with ...

I overlooked this one... Building a Win7 VM to test it out. Hang on. :)

**Comment by yatli** [comment]
btw, do you have matching vcredist installed on these older systems?
usually you'll need these guys:

```
concrt140.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
vccorlib140.dll
vcruntime140.dll
```

**Comment by yatli** [comment]
ok I've got a repro:

1. Build a bare-metal Hyper-V x64 VM with Windows 7 Ultimate SP1
2. Install `dotnet-sdk-2.1.402-win-gs-x64` (dotnet sdk)
3. Copy a project built with net471, referencing a freshly-built `GraphEngine.Core`, over to the VM, run it
    - It gives an error prompting to install newer .NET runtimes
4. Update Windows Update so that certificates are updated.
5. Install `NDP471-KB4033342-x86-x64-AllOS-ENU` (net471 runtime)
6. Run the built .exe again, it starts successfully, but throws error when loading `Trinity.dll`
7. Install `vcredist_x64` for Visual Studio 2017 and reboot -- you can find an installer in your VS2017 installation -- I've found it here: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.15.26706`
    - Now at least the command `dotnet` runs
    - The built program still fails.
8. Use dependency walker to probe the dependencies of `Trinity.dll` (http://www.dependencywalker.com/)
    - missing dependency `IESHIMS.dll` (wat?)
    - missing a few imports in dependency modules


So the thing is, this is not about a missing runtime component, more probably that our current build artifacts are not targeting earlier systems.
