### ISSUE TITLE
Dataset for freebase-likq sample does not exist

### ISSUE THREAD

**Issue by TaviTruman** [Microsoft/GraphEngine#342]
https://graphengine.blob.core.windows.net/public-data/freebase-full-dataset-20170410.zip file does not exist.

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The remote server returned an error: (404) The specified resource does not exist..)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at freebase_likq.Program.DownloadDataFile() in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 122
   at freebase_likq.Program.Initialize() in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 58
   at freebase_likq.Program.Main(String[] args) in O:\TrinityGraphEngine\GraphEngine\samples\freebase-likq\freebase-likq\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The remote server returned an error: (404) The specified resource does not exist..

**Comment by shaobin** [comment]
I noticed this issue. The Freebase demo project is outdated; and I've temporarily removed it from the repo. I may check in an updated demo project later. Stay tuned.

By the way, I'm in the process of bringing up to date the projects, including Graph Engine Core and the sample projects. One of the toolchain changes is that .NET 6 will be the mainly supported "Target Framework". @TaviTruman I know you are a heavy user of Graph Engine. Thank you for your constant support and help! If you have any most wanted features, please add comment to #344.

**Comment by TaviTruman** [comment]
@shaobin My pleasure Dr. Shao. Graph Engine is an awesome technology and is just what I needed to drive the technology I've been dreaming to create. I've got a long list of items on my Wishlist and have been working to implement albeit some very specific to building tools for ontology-driven software design and development, while others are more general purpose.
